### ISSUE TITLE
Fatal error: Call to a member function writeln() on null

### ISSUE THREAD

**Issue by rollecode** [chefsplate/groove-to-helpscout-migration-tool#7]
sync-customer worked just fine, but sync-tickets prints error like this:

```
[13:39:56] rolle groove-to-helpscout-migration-tool $ php artisan sync-tickets
[START] Starting sync of Groove tickets and messages at 2019-02-06T06:44:29-05:00
Validation check: ensuring each mailbox in Groove maps to a HelpScout mailbox

                                                            
  [Symfony\Component\Debug\Exception\FatalThrowableError]   
  Fatal error: Call to a member function writeln() on null  
                                                            
```

**Comment by rollecode** [comment]
laravel.log:

```
[2019-02-06 07:40:45] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to a member function writeln() on null in /home/rolle/groove-to-helpscout-migration-tool/vendor/laravel/framework/src/Illuminate/Console/Command.php:366
Stack trace:
#0 /home/rolle/groove-to-helpscout-migration-tool/app/Console/Commands/SyncCommandBase.php(107): Illuminate\Console\Command->line('Failed to retri...', 'error', NULL)
#1 /home/rolle/groove-to-helpscout-migration-tool/vendor/laravel/framework/src/Illuminate/Console/Command.php(402): App\Console\Commands\SyncCommandBase->line('Failed to retri...', 'error', NULL)
#2 /home/rolle/groove-to-helpscout-migration-tool/app/Console/Commands/APIHelper.php(64): Illuminate\Console\Command->error('Failed to retri...')
#3 /home/rolle/groove-to-helpscout-migration-tool/app/Console/Commands/APIHelper.php(132): App\Console\Commands\APIHelper::retrieveHelpscoutMailboxes()
#4 /home/rolle/groove-to-helpscout-migration-tool/app/Console/Commands/SyncTickets.php(86): App\Console\Commands\APIHelper::findMatchingMailboxByName('Digitoimisto Du...')
#5 /home/rolle/groove-to-helpscout-migration-tool/app/Console/Commands/SyncTickets.php(55): App\Console\Commands\SyncTickets->performInitialValidation()
#6 [internal function]: App\Console\Commands\SyncTickets->handle()
#7 /home/rolle/groove-to-helpscout-migration-tool/bootstrap/cache/compiled.php(1232): call_user_func_array(Array, Array)
#8 /home/rolle/groove-to-helpscout-migration-tool/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#9 /home/rolle/groove-to-helpscout-migration-tool/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/rolle/groove-to-helpscout-migration-tool/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/rolle/groove-to-helpscout-migration-tool/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/rolle/groove-to-helpscout-migration-tool/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\SyncTickets), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/rolle/groove-to-helpscout-migration-tool/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/rolle/groove-to-helpscout-migration-tool/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/rolle/groove-to-helpscout-migration-tool/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 {main}  
```

**Comment by rollecode** [comment]
Commented out try catch [here](https://github.com/chefsplate/groove-to-helpscout-migration-tool/blob/1040a5df7159bff9ebaa43b917170f9a983ad688/app/Console/Commands/APIHelper.php#L64) and got **[HelpScout\ApiException] Invalid API key**. I had copied oauth access token of api 2.0 instead of legacy API key, now it works. You should really improve exceptions...

**Comment by davidchchang** [comment]
Thanks for the feedback Roni - this looks new to 2.0; we admittedly haven't been maintaining this much as we are no longer using Groove for several years now and we've moved away from HelpScout as well. As always, pull requests to improve this are more than welcome.
